server.port=8086

spring.application.name=REPORT-SERVICE

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

jwt.secret=cGF5dHJhY2tzZWNyZXRrZXlwYXl0cmFja3NlY3JldGtleQ==
jwt.expiration=86400000